JDP230202-15
piotr-grosicki/project-jdp-2302-02 pull request #11
Opened 2023-02-03 21:17 UTC by JacekOstapczuk

2023-02-04 07:57 UTC, piotr-grosicki requested changes

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private int CartId;
nazwy zmiennych z malej liter, id to zwykle Longi (bylo dobrze przed zmiana)

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +private User user;
formatowanie

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/RandomKey.java
> +    public RandomKey activateKey(RandomKey randomKey) {
zupelnie nie rozumiem tej metody, czemu ona jest czescia klasy RandomKey i przyjmuje RandomKey jako parametr?

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/RandomKey.java
> +    LocalDate date1 = LocalDate.of(1990, 1, 1);
czemu to sa pola tej klasy + czemu maja defaultowy dostep?

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "IS_ACTIVE"  )
formatowanie

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
ta zmiana jest niedopuszczalna, nie chcemy overridowania beanow

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +
formatowanie

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @JoinColumn(name="USERS_CARTS")
czemu taka nazwa kolumny?

2023-02-04 07:57 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +   RandomKey randomKey = new RandomKey();
to nie jest dobre rozwiazanie ;) przemysl je od nowa

2023-02-04 16:30 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private int CartId;
poprawione

2023-02-04 16:30 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +private User user;
poprawione

2023-02-04 16:30 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/RandomKey.java
> +    public RandomKey activateKey(RandomKey randomKey) {
To część implementacji wymogu klucza aktywnego godzinę.
Idea w sktócie: klucz jest inicjowany zmiennymi domyślnymi (datas z 1990r. i int -1) które będą odczytywane jako nieaktywne. Potem wchodzi controller z metodą activateKey i zmienia te zmienne na losową liczbę i aktualna datę co pozwala na sprawdzenie potem ważności klucza.  tworząc encję musiałem albo stworzyć kolumnę RandomKey i kolejną encję przechowywyjącą pierwotne dane albo rozbić to już tu na zmienne akceptowane jako wkład do encji (key1=randomdatetime i key2=int)

2023-02-04 16:30 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/RandomKey.java
> +    LocalDate date1 = LocalDate.of(1990, 1, 1);
jak powyżej

2023-02-04 16:30 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "IS_ACTIVE"  )
zrobione

2023-02-04 16:30 UTC, JacekOstapczuk commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
bez tego się nie budowało, w którymś z submodułow była instrukcja zeby to dodać

2023-02-04 16:30 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +
zrobione

2023-02-04 16:32 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @JoinColumn(name="USERS_CARTS")
Tłumaczyłem to sobie jako koszyki użytkowników.

2023-02-04 16:38 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +   RandomKey randomKey = new RandomKey();
Hmmm....   miotam się jaką filozofię działania klucza przyjąć, mogę go wbudować w Usera jako dwie zmienne key1 i key2 ale na pewnym etapie myślałem, że może być teć potrzebny jako osobna klasa i tak by pewnie wyglądał w bardziej rozbudowanym projekcie. Starałem się jakoś to wypośrodkować.  Mogę uprościć jako :
key1= new LocalDateTime.of (newLocalDate(1990,1,1), LocalTime(1,1))
key2= -1
i potem w controlerze nadawać im inne wartości. Było by prościej i bez dodatkowej klasy.

2023-02-05 08:03 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/RandomKey.java
> +    public RandomKey activateKey(RandomKey randomKey) {
ja rozumiem idee, nie rozumiem czemu to jest tak napisane :) ze metoda, ktora jest w klasie RandomKey przyjmuje INNY RandomKey i na nim pracuje ;)

2023-02-05 08:04 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/RandomKey.java
> +    LocalDate date1 = LocalDate.of(1990, 1, 1);
nadal te same zastrzezenia jak napisalem, ja rozumiem idee, nie rozumiem dlaczego ten kod tak wyglada :)

2023-02-05 08:05 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +   RandomKey randomKey = new RandomKey();
najprosciej to po prostu dwa pola w klasie User, klucz i data waznosci, najpierw ustawione jako nulle. gdy ktos generuje klucz to po prostu go generujemy, wrzucamy w odpowiednie pole i ustawiamy date waznosci na godizne do przodu. bez uzycia dodatkowej klasy i duzo prosciej :)

2023-02-05 10:26 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/RandomKey.java
> +    public RandomKey activateKey(RandomKey randomKey) {
Chciałem obsługę klucza zamknąć w jednej klasie (generowanie, aktywacja, banowanie [metoda wynikająza z endpointa [zablokowanie użytkownika])

2023-02-05 10:48 UTC, closed without merging