Jdp230202 15.2
piotr-grosicki/project-jdp-2302-02 pull request #15
Opened 2023-02-05 10:53 UTC by JacekOstapczuk

2023-02-05 19:37 UTC, piotr-grosicki requested changes

2023-02-05 19:37 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    long userId;
pola encji powinny byc prywatne

2023-02-05 19:37 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
ponownie: bez tej zmiany :)

2023-02-05 19:44 UTC, JacekOstapczuk commented on src/main/resources/application.properties
> +spring.main.allow-bean-definition-overriding=true
poprawione

2023-02-05 19:44 UTC, JacekOstapczuk commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    long userId;
poprawione

2023-02-06 20:14 UTC, rafsmo1992 requested changes
wiersz 44 - List powinno być private

2023-02-06 21:25 UTC, rafsmo1992 approved these changes

2023-02-08 09:39 UTC, merged